# ! coop_assembly
# branches:
#   only:
#   - dev
#   except:
#   - dev

language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install Cython --install-option="--no-cython-compile"
install:
# This works because requirements-dev.txt ends with "-e ." to install COMPAS itself
  - pip install --no-cache-dir -r requirements-dev.txt
  # before these PRs are merged
  - pip install cmake
  - pip install -e git+git://github.com/yijiangh/compas_fab.git@feature/assembly_datastructure#egg=compas_fab
  - pip install -e git+git://github.com/yijiangh/pychoreo.git@test/extrusion_rss#egg=pychoreo
  - pip install scipy>=1.4.1

script:
# The new coverage version has some breaking changes and is not backwards
# compatible. See z4r/python-coveralls#73
  - pip install coverage==4.5.4
  - pip install python-coveralls
  - invoke test
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      invoke docs;
    fi

after_success:
  - coveralls
